version: '3.8'

services:
  # O serviço da sua aplicação agora expõe a porta diretamente.
  odsr-app:
    build: .
    image: odsr-app
    restart: always
    ports:
      # Mapeia a porta 8091 do seu servidor (host) para a porta 80
      # dentro do container da aplicação.
      - "8091:80"

# O serviço de proxy foi removido para simplificar a arquitetura
# e resolver o erro de montagem de volume.
